[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://parkpa.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[functions.api]
  included_files = ["functions/models/**"]
  timeout = 30

[build.environment]
  REACT_APP_API_URL = "/.netlify/functions/api"
